### ISSUE TITLE
Bugs in code

### ISSUE THREAD

**Issue by QwazyWabbitWOS** [tastyspleen/q2admin-tsmod#1]
In file zb_zbot.c, line 299 should be changed from:
             if (proxyinfo[client].msec_count = 500)
to:
             if (proxyinfo[client].msec_count == 500)

Line 1975 in file zb_ban.c the return 0 is unreachable code.

**Comment by tastyspleen** [comment]
Thanks!

Changes pushed.

`9c261b75462ea52ae1e363091afbc73cf30f7d13 BUG FIX: Unintended assignment in conditional.`
`e529320018bec8d17238d6256a7baec3cb68f4f4 Remove superfluous unreachable return statement.`
