### ISSUE TITLE
can't compil on raspberry pi 3B+ (ARM)

### ISSUE THREAD

**Issue by PowaBanga** [tastyspleen/q2admin-tsmod#5]
Hi, 
I can't compil Q2admin on my raspberry pi B+ (raspbian)
```
 make
gcc -std=gnu99 -O2 -fPIC -DARCH="arm" -DLINUX -DSTDC_HEADERS -I/usr/include   -c -o g_main.o g_main.c
g_main.c:52:3: error: #error Unknown architecture
  #error Unknown architecture
   ^~~~~
g_main.c: In function ‘GetGameAPI’:
g_main.c:230:36: error: ‘DLLNAME’ undeclared (first use in this function)
  sprintf(dllname, "%s/%s", moddir, DLLNAME);
                                    ^~~~~~~
g_main.c:230:36: note: each undeclared identifier is reported only once for each function it appears in
<commande interne> : la recette pour la cible « g_main.o » a échouée
make: *** [g_main.o] Erreur 1
```
hmm ... there is a way to fix that ?

**Comment by QwazyWabbitWOS** [comment]
It was a rather unwise choice by idSoftware to name their DLLs according to processor architecture.

The q2admin code needs to know what the successor DLL is named. It appears that your dday code has chosen to be called gamex86 even though you have compiled it on ARM, an architecture that didn't exist when Quake2 was originally written.

If it were me, I would name it game_arm.real.dll for all ARM targets and name q2admin game_arm.dll but I do not know what you have done about this issue in your q2pro code. It looks like you are keeping to the gamei386.so in your dday code.

Modify g_main.c in q2admin source at lines 37-58 to read as follows:
```
#ifdef __GNUC__
void *hdll = NULL;

#ifdef LINUXAXP
	#define DLLNAME   "gameaxp.real.so"
#elif defined(SOLARIS_INTEL)
	#define DLLNAME   "gamei386.real.so"
#elif defined(SOLARIS_SPARC)
	#define DLLNAME   "gamesparc.real.so"
#elif defined (LINUX)
#if defined __i386__
	#define DLLNAME "gamei386.real.so"
#elif defined __x86_64__
	#define DLLNAME "gamex86_64.real.so"
#elif defined __arm__
	#define DLLNAME "gamei386.real.so"
#else
	#error Unknown architecture
#endif
#else
	#error Unknown GNUC OS
#endif
```

**Comment by QwazyWabbitWOS** [comment]
ARRGGHH!!!

HTML Markdown is messing up the text.
The bold items should be preceded and followed by double-underscores in your source code.

**Comment by PowaBanga** [comment]
you should put your text in this markdown : 
````
```
code here
```
````

**Comment by QwazyWabbitWOS** [comment]
I did it that way the first time. It still screwed it up but I will try again in a little while.

**Comment by QwazyWabbitWOS** [comment]
"It can only be attributable to human error."

**Comment by PowaBanga** [comment]
ok, I compiled it on arm simply by adding : 
```
#elif defined __arm__
	#define DLLNAME "gamearm.real.so"
#else
```
simply where you suggested it, it work realy good thank you, I will certainly do a pull request later

**Comment by QwazyWabbitWOS** [comment]
Excellent. 
If you want, you can also remove the regex.o reference in the GNUmakefile and make all and it will use the internal regex support of the runtime rather than the regex.c needed by WIN32.

**Comment by PowaBanga** [comment]
So, English is not my native langage... I really do not understand what is regex... What is its usefulness exactly ?

**Comment by QwazyWabbitWOS** [comment]
Regex stands for regular expression, this was a POSIX library. The original author of Q2admin, Shane Powell, used this functionality for parsing commands and strings when applying bans and masks and all the administrative tasks Q2admin does. It saved him time writing it all from scratch. The Windows builds needed it but the LINUX builds don't since the POSIX support is already there. regex.c and regex.h in the Q2admin source are strictly for Windows builds and it looks like that code is fairly old anyway.
